// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxdyhisurvpbucbdvcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneGR5aGlzdXJ2cGJ1Y2JkdmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDU4ODUsImV4cCI6MjA2NjU4MTg4NX0.3vCgkOMHwDYCyqk2FTYCund2oqAcjkXbT7_Yotm-oGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);